spring:
  data:
    solr:
      host: http://192.168.80.136:8983/solr/ik_core
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123


